package org.kotlinrl.integration.gymnasium

import org.kotlinrl.core.env.BoxNDArrayDoubleD1BoxNDArrayFloatD1Env
import org.kotlinrl.core.env.BoxNDArrayFloatD1BoxNDArrayFloatD1Env
import org.kotlinrl.core.env.BoxNDArrayFloatD1DiscreteEnv
import org.kotlinrl.core.env.DiscreteDiscreteEnv

typealias CartPoleEnv = BoxNDArrayFloatD1DiscreteEnv
typealias AcrobotEnv = BoxNDArrayFloatD1DiscreteEnv
typealias MountainCarEnv = BoxNDArrayFloatD1DiscreteEnv
typealias LunarLanderEnv = BoxNDArrayFloatD1DiscreteEnv
typealias FrozenLakeEnv = DiscreteDiscreteEnv
typealias CliffWalkingEnv = DiscreteDiscreteEnv
typealias TaxiEnv = DiscreteDiscreteEnv
typealias PendulumEnv = BoxNDArrayFloatD1BoxNDArrayFloatD1Env
typealias AntEnv = BoxNDArrayDoubleD1BoxNDArrayFloatD1Env
typealias BipedalWalkerEnv = BoxNDArrayFloatD1BoxNDArrayFloatD1Env
typealias MountainCarContinuousEnv = BoxNDArrayFloatD1BoxNDArrayFloatD1Env