package io.github.kotlinrl.core.algorithms.mc

import io.github.kotlinrl.core.*

/**
 * Implements the Off-Policy Monte Carlo Control algorithm for reinforcement learning.
 *
 * This class is designed to estimate the Q-function and improve the policy using data
 * collected from episodes generated by a behavioral policy while targeting an optimal
 * policy. The behavioral policy is used to explore the environment, and the Q-function
 * is updated using importance sampling techniques. The target policy is then updated
 * by improving it based on the estimated Q-function. The algorithm is designed to be
 * trajectory-based, with updates applied on a per-trajectory basis.
 *
 * @param State the type representing the environment's states.
 * @param Action the type representing the actions that can be taken in the environment.
 * @param behavioralPolicy the policy used to generate exploratory trajectories.
 * @param targetPolicy the policy being optimized by the algorithm.
 * @param gamma the discount factor for future rewards, representing their relative importance.
 * @param estimator the mechanism used to estimate the Q-function using trajectories and
 *        importance sampling. Defaults to `OffPolicyMonteCarloQFunctionEstimator`.
 * @param onQFunctionUpdate a callback triggered after Q-function updates.
 * @param onPolicyUpdate a callback triggered after policy updates.
 */
class OffPolicyMonteCarloControl<State, Action>(
    behavioralPolicy: QFunctionPolicy<State, Action>,
    targetPolicy: QFunctionPolicy<State, Action>,
    gamma: Double,
    estimator: TrajectoryQFunctionEstimator<State, Action> = OffPolicyMonteCarloQFunctionEstimator(
        initTargetPolicy = targetPolicy,
        behaviorPolicy = behavioralPolicy,
        gamma = gamma,
    ),
    onQFunctionUpdate: EnumerableQFunctionUpdate<State, Action> = { },
    onPolicyUpdate: PolicyUpdate<State, Action> = { },
) : TrajectoryQFunctionAlgorithm<State, Action>(
    initialPolicy = behavioralPolicy,
    estimator = estimator,
    onQFunctionUpdate = onQFunctionUpdate,
    onPolicyUpdate = {
        when (estimator) {
            is OffPolicyMonteCarloQFunctionEstimator -> estimator.targetPolicy =
                it.improve((it as QFunctionPolicy<State, Action>).Q)
        }
        onPolicyUpdate(it)
    }
)