package io.github.kotlinrl.core.algorithms.mc

import io.github.kotlinrl.core.*

/**
 * Implements the Off-Policy Monte Carlo Value Function Estimator algorithm for reinforcement learning.
 *
 * This class estimates the state-value function using trajectory data collected from episodes
 * generated by a behavior policy, while targeting an optimal policy. The estimation is performed
 * using importance sampling techniques to correct for the discrepancy between the behavior
 * policy and the target policy. The algorithm incorporates the concept of weighted returns
 * to update the value function incrementally based on observed rewards.
 *
 * The value function is updated using trajectories with a reverse iteration approach. The method
 * scales the contribution of each state in the trajectory to the value function using the ratio of
 * the target policy's probability to the behavior policy's probability of selecting actions. The
 * correction factor (importance weight) ensures unbiased estimation under off-policy sampling.
 *
 * @param State the type representing the environment's states.
 * @param Action the type representing the actions that can be taken in the environment.
 * @param gamma the discount factor for future rewards, representing their relative importance.
 * @param behaviorPolicy the policy used to generate exploratory trajectories.
 * @param targetPolicy the policy being optimized or evaluated.
 */
class OffPolicyMonteCarloValueFunctionEstimator<State, Action>(
    private val gamma: Double,
    private val behaviorPolicy: StochasticPolicy<State, Action>,
    private var targetPolicy: Policy<State, Action>,
) : TrajectoryValueFunctionEstimator<State, Action> {

    private val C: MutableMap<Comparable<*>, Double> = mutableMapOf()

    /**
     * Estimates the updated enumerable value function for a given state-space and trajectory
     * using Off-Policy Monte Carlo estimation with importance sampling.
     *
     * This method iterates through the provided trajectory in reverse, computing the cumulative
     * discounted reward (return G) and adjusting the value function accordingly. The update process
     * utilizes importance sampling ratios to correct for the difference between the behavior policy
     * and the target policy. The estimation halts earlier if the importance sampling ratio reaches
     * zero or if an action in the trajectory does not match the target policy.
     *
     * @param V the initial enumerable value function to be updated based on the trajectory.
     * @param trajectory the trajectory of states, actions, and rewards used to compute the updates
     * to the value function.
     * @return the updated enumerable value function reflecting estimates derived from the trajectory.
     */
    override fun estimate(V: EnumerableValueFunction<State>, trajectory: Trajectory<State, Action>): EnumerableValueFunction<State> {
        var G = 0.0
        var W = 1.0
        var newV = V

        for ((s, a, r) in trajectory.asReversed()) {
            G = r + gamma * G
            val key = s.toComparable()

            val c = C.getOrDefault(key, 0.0) + W
            C[key] = c

            val oldV = newV[s]
            val newValue = oldV + (W / c) * (G - oldV)
            newV = newV.update(s, newValue)

            if (a != targetPolicy(s)) break

            val prob = behaviorPolicy.probability(s, a)
            if (prob == 0.0) break
            W /= prob
        }

        return newV
    }
}
