package io.github.kotlinrl.core.algorithms.mc

import io.github.kotlinrl.core.*
import io.github.kotlinrl.core.algorithms.base.EstimateQ_fromTrajectory

/**
 * Implements an off-policy Monte Carlo approach for estimating the Q-function from a trajectory
 * of state-action-reward transitions. This class utilizes weighted importance sampling to update
 * the Q-function and improve the target policy, refining the evaluation of state-action pairs
 * towards optimal behavior.
 *
 * This algorithm processes trajectories generated by a behavioral policy while optimizing
 * a separate target policy. It incorporates importance weights to compensate for differences
 * between the behavioral and target policies, ensuring convergence towards an optimal policy
 * even under differing sampling distributions.
 *
 * @param State the type representing the states in the environment.
 * @param Action the type representing the actions that can be performed in the environment.
 * @param initTargetPolicy the initial greedy policy that will be updated iteratively towards optimality.
 * @param behaviorPolicy the policy used to generate the trajectories during the agent's interaction with the environment.
 * @param gamma the discount factor used to compute the return, controlling the consideration of future rewards.
 */
class OffPolicyMonteCarloEstimateQ_fromTrajectory<State, Action>(
    initTargetPolicy: Policy<State, Action>,
    private val behaviorPolicy: Policy<State, Action>,
    private val gamma: Double,
) : EstimateQ_fromTrajectory<State, Action> {
    private val C: MutableMap<StateActionKey<*, *>, Double> = mutableMapOf()

    /**
     * Represents the target policy being optimized in the off-policy Monte Carlo learning algorithm.
     *
     * The target policy is what the algorithm aims to improve during the learning process. It is distinct
     * from the behavior policy used to generate trajectories, and updates to this policy are driven by
     * the Q-function refinements resulting from off-policy importance sampling and other learning mechanisms.
     *
     * This policy dictates the optimal behavior the agent should ideally follow, and it evolves iteratively
     * with the algorithm's progression.
     */
    var targetPolicy: Policy<State, Action> = initTargetPolicy

    /**
     * Performs an off-policy Monte Carlo Q-function estimation using weighted importance sampling.
     * The function processes the provided trajectory in reverse order to compute returns (`G`)
     * and updates the Q-function for each state-action pair encountered. The weights (`W`) adjust
     * the updates based on the importance sampling ratio, computed as the probability of the action
     * under the behavioral policy compared to the target policy.
     *
     * @param Q the initial Q-function, mapping state-action pairs to expected returns.
     * @param trajectory a trajectory containing a sequence of state-action-reward triples.
     * @return the updated Q-function after applying off-policy importance sampling corrections.
     */
    override operator fun invoke(
        Q: QFunction<State, Action>,
        trajectory: Trajectory<State, Action>
    ): QFunction<State, Action> {
        var G = 0.0
        var W = 1.0
        var currentQ = Q

        for ((s, a, r) in trajectory.asReversed()) {
            G = r + gamma * G

            val key = StateActionKey(s, a)
            val oldC = C.getOrDefault(key, 0.0)
            val newC = oldC + W
            C[key] = newC

            val oldQ = currentQ[s, a]
            val updatedQ = oldQ + (W / newC) * (G - oldQ)
            currentQ = currentQ.update(s, a, updatedQ)

            if (a != targetPolicy(s)) break
            val prob = behaviorPolicy.probability(s, a)
            if (prob == 0.0) break
            W /= prob
        }

        return currentQ
    }
}
