package io.github.kotlinrl.core.algorithms.mc

import io.github.kotlinrl.core.*

/**
 * Implements the On-Policy Monte Carlo Control algorithm for reinforcement learning.
 *
 * This algorithm estimates the Q-function and improves the policy directly using trajectories
 * generated by the current policy. It utilizes Monte Carlo estimation to update action-value
 * estimates based on observed returns, and subsequently refines the policy according to the
 * updated Q-function. The updates are applied trajectory-by-trajectory, ensuring an iterative
 * improvement of both the Q-function and the policy.
 *
 * Key features include:
 * - Supports both first-visit and every-visit Monte Carlo methods through the `firstVisitOnly` parameter.
 * - Integrates a customizable Q-function estimator and callbacks for policy and Q-function updates.
 *
 * @param State the type representing the environment's states.
 * @param Action the type representing the actions that can be taken in the environment.
 * @param initialPolicy the initial policy used to start the learning process. The policy is updated dynamically.
 * @param gamma the discount factor for future rewards, indicating their relative importance in determining returns.
 * @param firstVisitOnly a Boolean flag indicating whether to use a first-visit Monte Carlo method. Defaults to true.
 * @param estimator the mechanism used to estimate the Q-function from trajectories. Defaults to
 *        `OnPolicyMonteCarloQFunctionEstimator` with the specified `gamma` and `firstVisitOnly` values.
 * @param onQFunctionUpdate a callback executed after each Q-function update.
 * @param onPolicyUpdate a callback executed after each policy update.
 */
class OnPolicyMonteCarloControl<State, Action>(
    initialPolicy: QFunctionPolicy<State, Action>,
    gamma: Double,
    firstVisitOnly: Boolean = true,
    estimator: TrajectoryQFunctionEstimator<State, Action> = OnPolicyMonteCarloQFunctionEstimator(
        gamma,
        firstVisitOnly
    ),
    onQFunctionUpdate: EnumerableQFunctionUpdate<State, Action> = { },
    onPolicyUpdate: PolicyUpdate<State, Action> = { }
) : TrajectoryQFunctionAlgorithm<State, Action>(initialPolicy, estimator, onPolicyUpdate, onQFunctionUpdate)

