package io.github.kotlinrl.core.algorithms.mc

import io.github.kotlinrl.core.*

/**
 * Implements the On-Policy Monte Carlo Value Function Estimation algorithm.
 *
 * This class estimates the state-value function (`V(s)`) based on trajectories
 * generated by a given on-policy strategy. It uses Monte Carlo methods to update
 * the value function, leveraging cumulative returns from sampled trajectories.
 *
 * The estimator supports both first-visit and every-visit Monte Carlo methods,
 * controlled via the `firstVisitOnly` parameter:
 * - First-visit Monte Carlo updates the value function only at the first occurrence
 *   of each state in a trajectory.
 * - Every-visit Monte Carlo updates the value function at every occurrence
 *   of a state in the trajectory.
 *
 * Key functionalities include:
 * - Use of a discount factor, `gamma`, to calculate cumulative returns.
 * - Maintenance of running averages for state-value estimates using counts
 *   of returns observed for each state and their accumulated sums.
 *
 * @param State the type representing the environment's states.
 * @param Action the type representing the actions that can be executed in the environment.
 * @param gamma the discount factor for future rewards. Determines the weight of future rewards relative to immediate rewards.
 * @param firstVisitOnly a Boolean specifying whether to use the first-visit Monte Carlo method. Defaults to true.
 */
class OnPolicyMonteCarloValueFunctionEstimator<State, Action>(
    private val gamma: Double,
    private val firstVisitOnly: Boolean = true,
) : TrajectoryValueFunctionEstimator<State, Action> {

    private val returnsCount: MutableMap<Comparable<*>, Int> = mutableMapOf()
    private val returnsSum: MutableMap<Comparable<*>, Double> = mutableMapOf()

    override fun estimate(V: EnumerableValueFunction<State>, trajectory: Trajectory<State, Action>): EnumerableValueFunction<State> {
        val visited = mutableSetOf<Comparable<*>>()
        var G = 0.0
        var updatedV = V

        for ((s, _, r) in trajectory.asReversed()) {
            G = r + gamma * G
            val key = stateKey(s)

            if (firstVisitOnly && key in visited) continue
            visited.add(key)

            val count = returnsCount.getOrDefault(key, 0) + 1
            val sum = returnsSum.getOrDefault(key, 0.0) + G

            returnsCount[key] = count
            returnsSum[key] = sum

            val averageReturn = sum / count
            updatedV = updatedV.update(s, averageReturn)
        }

        return updatedV
    }
}
